openapi: 3.1.0
info:
  title: Review API
  version: 1.0.0
components:
  schemas:
    Review:
      type: object
      properties:
        _id:
          type: string
        productId:
          type: string
          description: id of the product being reviewed
        userId:
          type: string
        rating:
          type: number
          minimum: 0
          maximum: 5
        title:
          type: string
          description: title of the review
        body:
          type: string
          description: User's opinions on the product
        date:
          type: number
          description: Unix timestamp of when the review was created
      required:
        - _id
        - productId
        - userId
        - rating
        - title
        - date
paths:
  /reviews:
    get:
      summary: List all reviews
      responses:
        "200":
          description: A list of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"
    post:
      summary: Create a new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Review"
      responses:
        "201":
          description: Review created
