openapi: 3.1.0
info:
  title: User API
  version: 1.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        image:
          type: string
          format: uri
        name:
          type: string
        quantity:
          type: integer
          minimum: 1
        price:
          type: integer
          minimum: 0
        brand:
          type: string
      required: [image, name, quantity, price]

    User:
      type: object
      properties:
        _id:
          type: string
        firstName:
          type: string
          description: User's first name
        lastName:
          type: string
          description: User's last name
        email:
          type: string
          format: email
          description: User email (unique)
        password:
          type: string
          description: User password
        cart:
          type: array
          description: Array of productIds in the user's cart
          items:
            $ref: '#/components/schemas/Product'
        wishlist:
          type: array
          description: Array of productIds in the user's wishlist
          items:
            type: string
        Auth_ID:
          type: string
          description: Result from auth login (unique)
      required:
        - _id
        - firstName
        - lastName
        - email
        - password
        - cart
        - wishlist
paths:
  /users:
    get:
      summary: List all users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created
